// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-09-20 16:16:16.085021 +0800 CST m=+0.981644314
// using data from
// https://github.com/golang/go/raw/master/CONTRIBUTORS
package project

var Contributors = []string{
	"Carl Chatfield <carlchatfield@gmail.com>",
	"Carl Henrik Lunde <chlunde@ifi.uio.no>",
	"Carl Jackson <carl@stripe.com>",
	"Carl Johnson <me@carlmjohnson.net>",
	"Carl Mastrangelo <notcarl@google.com>",
	"Carl Shapiro <cshapiro@google.com> <cshapiro@golang.org>",
	"Carlisia Campos <carlisia@grokkingtech.io>",
	"Carlo Alberto Ferraris <cafxx@strayorange.com>",
	"Carlos Castillo <cookieo9@gmail.com>",
	"Carlos Cirello <uldericofilho@gmail.com>",
	"Carlos Eduardo <me@carlosedp.com>",
	"Carlos Eduardo Seo <cseo@linux.vnet.ibm.com>",
	"Carlos Souza <carloshrsouza@gmail.com>",
	"David Carlier <devnexen@gmail.com>",
	"Dustin Carlino <dcarlino@google.com>",
	"Juan Carlos <juanjcsr@gmail.com>",
}
